version: 2
project_name: bagel

before:
  hooks:
    - go mod verify

builds:
  - main: ./cmd/bagel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes" # skip user interaction
    artifacts: checksum
    output: true

archives:
  - formats: [ 'zip' ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
